import '@material/mwc-icon-button';
import "@material/mwc-tab-bar";
import "@material/mwc-top-app-bar";
import "@material/mwc-textfield";
import "@material/mwc-fab";
import "@material/mwc-textarea";
import "@material/mwc-formfield";
import "@vanillawc/wc-markdown";
//# sourceMappingURL=materialLoader.d.ts.map